//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTEXERP.SResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTEXERP.SResources.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer Name.
        /// </summary>
        public static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code1 {
            get {
                return ResourceManager.GetString("Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code ....
        /// </summary>
        public static string CodePH {
            get {
                return ResourceManager.GetString("CodePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person PhoneNo.
        /// </summary>
        public static string ContactPersonPhoneNo {
            get {
                return ResourceManager.GetString("ContactPersonPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted Unit.
        /// </summary>
        public static string ConvertedUnit {
            get {
                return ResourceManager.GetString("ConvertedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted Unit ....
        /// </summary>
        public static string ConvertedUnitPH {
            get {
                return ResourceManager.GetString("ConvertedUnitPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type.
        /// </summary>
        public static string CurrencyType {
            get {
                return ResourceManager.GetString("CurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type ....
        /// </summary>
        public static string CurrencyTypePH {
            get {
                return ResourceManager.GetString("CurrencyTypePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Join.
        /// </summary>
        public static string DateOfJoin {
            get {
                return ResourceManager.GetString("DateOfJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/DD/YYYY ....
        /// </summary>
        public static string DatePH {
            get {
                return ResourceManager.GetString("DatePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description .....
        /// </summary>
        public static string DescriptionPH {
            get {
                return ResourceManager.GetString("DescriptionPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionFYCI ......
        /// </summary>
        public static string DesFYCI {
            get {
                return ResourceManager.GetString("DesFYCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equivalent Quantity.
        /// </summary>
        public static string EquivalentQuantity {
            get {
                return ResourceManager.GetString("EquivalentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equivalent Quantity ....
        /// </summary>
        public static string EquivalentQuantityPH {
            get {
                return ResourceManager.GetString("EquivalentQuantityPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English letters not allowed.
        /// </summary>
        public static string ErrEngNotAllowed {
            get {
                return ResourceManager.GetString("ErrEngNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special character not allowed (#, @ ...).
        /// </summary>
        public static string ErrSpecCharNotAllowed {
            get {
                return ResourceManager.GetString("ErrSpecCharNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Date.
        /// </summary>
        public static string EstimatedDate {
            get {
                return ResourceManager.GetString("EstimatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabric.
        /// </summary>
        public static string Fabric {
            get {
                return ResourceManager.GetString("Fabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabric Category Name.
        /// </summary>
        public static string FabricCategoryName {
            get {
                return ResourceManager.GetString("FabricCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabric Type Name.
        /// </summary>
        public static string FabricTypeName {
            get {
                return ResourceManager.GetString("FabricTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabric YarnComposition Name.
        /// </summary>
        public static string FabricYarnCompositionName {
            get {
                return ResourceManager.GetString("FabricYarnCompositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garment CategoryName.
        /// </summary>
        public static string GarmentCategoryName {
            get {
                return ResourceManager.GetString("GarmentCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garment Code.
        /// </summary>
        public static string GarmentCode {
            get {
                return ResourceManager.GetString("GarmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garment Type.
        /// </summary>
        public static string GarmentType {
            get {
                return ResourceManager.GetString("GarmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garment TypeName.
        /// </summary>
        public static string GarmentTypeName {
            get {
                return ResourceManager.GetString("GarmentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Wise ProductType Name.
        /// </summary>
        public static string GProTypeName {
            get {
                return ResourceManager.GetString("GProTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Child.
        /// </summary>
        public static string HasChild {
            get {
                return ResourceManager.GetString("HasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.Tax Acc.
        /// </summary>
        public static string IncomeTaxAccount {
            get {
                return ResourceManager.GetString("IncomeTaxAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.Tax Amt.
        /// </summary>
        public static string IncomeTaxAmount {
            get {
                return ResourceManager.GetString("IncomeTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.Tax %.
        /// </summary>
        public static string IncomeTaxPercentage {
            get {
                return ResourceManager.GetString("IncomeTaxPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Classification.
        /// </summary>
        public static string LabelClassification {
            get {
                return ResourceManager.GetString("LabelClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Type.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length ....
        /// </summary>
        public static string LengthPH {
            get {
                return ResourceManager.GetString("LengthPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name ....
        /// </summary>
        public static string NamePH {
            get {
                return ResourceManager.GetString("NamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (BN).
        /// </summary>
        public static string NameUc {
            get {
                return ResourceManager.GetString("NameUc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (BN) ....
        /// </summary>
        public static string NameUcPH {
            get {
                return ResourceManager.GetString("NameUcPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Pattern Pieces.
        /// </summary>
        public static string NoOfPatternPieces {
            get {
                return ResourceManager.GetString("NoOfPatternPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 2.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Code.
        /// </summary>
        public static string PhoneCode {
            get {
                return ResourceManager.GetString("PhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Code ....
        /// </summary>
        public static string PhoneCodePH {
            get {
                return ResourceManager.GetString("PhoneCodePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Size.
        /// </summary>
        public static string ProductSize {
            get {
                return ResourceManager.GetString("ProductSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season ....
        /// </summary>
        public static string SeasonPH {
            get {
                return ResourceManager.GetString("SeasonPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Basis.
        /// </summary>
        public static string SeriesBasis {
            get {
                return ResourceManager.GetString("SeriesBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series ....
        /// </summary>
        public static string SeriesPH {
            get {
                return ResourceManager.GetString("SeriesPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Range TypeName.
        /// </summary>
        public static string SizeRangeTypeName {
            get {
                return ResourceManager.GetString("SizeRangeTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        public static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        public static string StateNamePH {
            get {
                return ResourceManager.GetString("StateNamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Category.
        /// </summary>
        public static string TrimCategory {
            get {
                return ResourceManager.GetString("TrimCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        public static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        public static string UserCodePH {
            get {
                return ResourceManager.GetString("UserCodePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.A.T Acc.
        /// </summary>
        public static string VatAccount {
            get {
                return ResourceManager.GetString("VatAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.A.T Amt.
        /// </summary>
        public static string VatAmount {
            get {
                return ResourceManager.GetString("VatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.A.T %.
        /// </summary>
        public static string VatPercentage {
            get {
                return ResourceManager.GetString("VatPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthPH {
            get {
                return ResourceManager.GetString("WidthPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string YearPH {
            get {
                return ResourceManager.GetString("YearPH", resourceCulture);
            }
        }
    }
}
