using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace RTEXERP.DBEntities.Hrm.DbViews
{
    public class Tbl_CHirarchy
    {
        [Key]
        public long   Emp_ID                    {get;set;}
    public string Emp_Cd { get; set; }
    public int Emp_Company { get; set; }
    public int Emp_Dept { get; set; }
    public int Emp_Section { get; set; }
    public int Emp_Designation { get; set; }
    public int Emp_Shift { get; set; }
    public DateTime? Emp_Appointment { get; set; }
    public DateTime? Emp_Confirmation { get; set; }
    public DateTime? Emp_lastincrement { get; set; }
    public double? Emp_lastincamount { get; set; }
    public string Emp_Salutation { get; set; }
    public string Emp_Fname { get; set; }
    public string Emp_Mname { get; set; }
    public string Emp_Lname { get; set; }
    public string Emp_Father { get; set; }
    public string Emp_SSN { get; set; }
    public string Emp_Citizen { get; set; }
    public int? Emp_Marital { get; set; }
    public string Emp_Gender { get; set; }
    public DateTime? Emp_DOB { get; set; }
    public string Emp_PlaceofBirth { get; set; }
    public string Emp_Address1 { get; set; }
    public string Emp_City1 { get; set; }
    public string Emp_State1 { get; set; }
    public string Emp_Zip1 { get; set; }
    public int? Emp_Country1 { get; set; }
    public string Emp_Address2 { get; set; }
    public string Emp_City2 { get; set; }
    public string Emp_State2 { get; set; }
    public string Emp_Zip2 { get; set; }
    public int? Emp_Country2 { get; set; }
    public string Emp_Acode1 { get; set; }
    public string Emp_Tel1 { get; set; }
    public string Emp_Acode2 { get; set; }
    public string Emp_Tel2 { get; set; }
    public string Emp_Acode3 { get; set; }
    public string Emp_Tel3 { get; set; }
    public string Emp_Mobile { get; set; }
    public string Emp_Email { get; set; }
    public DateTime? Emp_Created { get; set; }
    public bool? Emp_Active { get; set; }
    public DateTime Emp_BlockDate { get; set; }
    public int? Emp_Religion { get; set; }
    public string Emp_Sect { get; set; }
    public string Emp_Race { get; set; }
    public double? Emp_Gross { get; set; }
    public double? Emp_Incentives { get; set; }
    public double? Emp_Salary { get; set; }
    public bool? Emp_Deleted { get; set; }
    public int AttendanceAllowance { get; set; }
    public int ConductAllowance { get; set; }
    public int HoliDayAllowance { get; set; }
    public int ExtraAllowance { get; set; }
    public int nighAllowance { get; set; }
    public int FestivalAllowance { get; set; }
    public double? TaxDeduction { get; set; }
    public int Emp_Bank { get; set; }
    public bool? Emp_AttAllow { get; set; }
    public string Emp_Name { get; set; }
    public string Emp_License { get; set; }
    public int Emp_LCountry { get; set; }
    public DateTime? Emp_LIssue { get; set; }
    public DateTime? Emp_LExpiry { get; set; }
    public string Emp_Ext { get; set; }
    public int emp_type { get; set; }
    public bool? Emp_Payroll { get; set; }
    public string Emp_Interviewed { get; set; }
    public string Emp_oldNo { get; set; }
    public string Emp_SSN2 { get; set; }
    public string Emp_User { get; set; }
    public string Emp_SSN_Deduction { get; set; }
    public string Emp_EOBI_Deduction { get; set; }
    public string Emp_Proximity { get; set; }
    public string Emp_RestDay { get; set; }
    public bool? Emp_PermanentlyBlocked { get; set; }
    public string Emp_BlockReason { get; set; }
    public bool? Emp_halfdayallowed { get; set; }
    public string Emp_LegacyCategory { get; set; }
    public string Emp_MotherName { get; set; }
    public string Emp_Bname { get; set; }
    public string Emp_FBname { get; set; }
    public string Emp_MBname { get; set; }
    public string Emp_taddress { get; set; }
    public string Emp_baddress { get; set; }
    public string Emp_VoterID { get; set; }
    public string Emp_MobileN { get; set; }
    public int Designation_Id { get; set; }
    public string Designation_Cd { get; set; }
    public string Designation_Name { get; set; }
    public int Designation_Grade { get; set; }
    public int Designation_Cadre { get; set; }
    public DateTime? Designation_Created { get; set; }
    public bool? Designation_Active { get; set; }
    public string Designation_Old { get; set; }
    public string Designation_OldC { get; set; }
    public int Designation_TextileGrade { get; set; }
    public int Designation_GarmentGrade { get; set; }
    public string Designation_Bname { get; set; }
    public string Designation_subname { get; set; }
    public string Designation_sub { get; set; }
    public int Dept_ID { get; set; }
    public string Dept_CD { get; set; }
    public string Dept_Name { get; set; }
    public int? Dept_Division { get; set; }
    public string Dept_Color { get; set; }
    public DateTime? Dept_Created { get; set; }
    public int Dept_User { get; set; }
    public bool? Dept_Active { get; set; }
    public int Dept_FinanceID { get; set; }
    public int Dept_Finance_GrossAccount { get; set; }
    public string Dept_BName { get; set; }
    public string Dept_subname { get; set; }
    public int Division_ID { get; set; }
    public string Division_Cd { get; set; }
    public string Division_Name { get; set; }
    public int? Division_Company { get; set; }
    public DateTime? Division_Created { get; set; }
    public bool? Division_Active { get; set; }
    public string Division_Color { get; set; }
    public int RegulatoryAuthority { get; set; }
    public string Division_BName { get; set; }
    public int Section_Id { get; set; }
    public string Section_Cd { get; set; }
    public string Section_Name { get; set; }
    public DateTime? Section_Created { get; set; }
    public bool? Section_Active { get; set; }
    public int Section_Dept { get; set; }
    public int Section_Location { get; set; }
    public string Section_Color { get; set; }
    public string Section_DeptOld { get; set; }
    public string Section_Loc { get; set; }
    public string Section_BName { get; set; }
    public int Cmp_ID { get; set; }
    public string Cmp_Name { get; set; }
    public int Cmp_Established { get; set; }
    public string Cmp_Address { get; set; }
    public string Cmp_City { get; set; }
    public string Cmp_State { get; set; }
    public string Cmp_Zip { get; set; }
    public int Cmp_Country { get; set; }
    public string Cmp_Tel1 { get; set; }
    public string Cmp_Tel2 { get; set; }
    public string Cmp_Fax { get; set; }
    public string Cmp_Web { get; set; }
    public string Cmp_Email { get; set; }
    public string Cmp_EOBI { get; set; }
    public string Cmp_Contact { get; set; }
    public int Cmp_MinAge { get; set; }
    public int Cmp_MaxAge { get; set; }
    public string BanglaCName { get; set; }
    public int Location_Id { get; set; }
    public string Location_Cd { get; set; }
    public string Location_Name { get; set; }
    public int? Location_Company { get; set; }
    public DateTime? Location_Created { get; set; }
    public int Physique_Emp { get; set; }
    public string Physique_Face { get; set; }
    public string Physique_Hair { get; set; }
    public string Physique_Eyes { get; set; }
    public double? Physique_Height { get; set; }
    public double? Physique_Wt { get; set; }
    public string Physique_Blood { get; set; }
    public string Physique_Imark { get; set; }
    public DateTime? Physique_Created { get; set; }
    public string EmpCd { get; set; }
    public int? Type_ID { get; set; }
    public string Type_CD { get; set; }
    public string Type_Name { get; set; }
    public int Type_Company { get; set; }
    public int? Type_Payroll { get; set; }
    public DateTime? Type_Created { get; set; }
    public string Type_NameBn { get; set; }
    public int? Religion_ID { get; set; }
    public string Religion_Name { get; set; }
}
}
